---
- hosts: webservers
  user: vagrant
  become: yes
  vars:
    apache_version: 2.6
    motd_warning: "WARNING: used by ICT faculty/students only.\n"
    testserver: yes
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
    
    - name: restart Apache
      service: 
        name: apache2
        state: restarted
