---
- name: update motd file
  hosts: ungrouped
  user: vagrant
  vars:
    apache_version: 2.6
    motd_warning: "WARNING: used by ICT faculty/students only.\n"
    testserver: yes
  tasks:
    - name: setup a Message Of The Day
      copy:
        dest: /etc/motd
        content: "{{ motd_warning }}"
